# Generated by Django 4.2.6 on 2024-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
